version: '3.8'

services:
  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # API сервис
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./src/data:/app/src/data:ro
    restart: unless-stopped
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

  # Воркер миграции
  migration-worker:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./src/data:/app/src/data:ro
    restart: unless-stopped
    command: python -m src.workers.migration_worker
    profiles:
      - migration

  # Воркер классификации - первый этап (все коллекции)
  classification-worker-1:
    build: .
    env_file:
      - .env
    environment:
      - WORKER_ID=worker_${WORKER_NUMBER:-1}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./src/data:/app/src/data:ro
    restart: unless-stopped
    command: python -m src.workers.classification_worker --worker-id worker_${WORKER_NUMBER:-1}
    profiles:
      - workers

  # Воркер классификации для конкретной коллекции
  classification-worker-collection:
    build: .
    env_file:
      - .env
    environment:
      - WORKER_ID=worker_${COLLECTION:-default}
      - REDIS_URL=redis://redis:6379
      - SOURCE_COLLECTION_NAME=${COLLECTION:-}
    depends_on:
      - redis
    volumes:
      - ./src/data:/app/src/data:ro
    restart: unless-stopped
    command: python -m src.workers.classification_worker --worker-id worker_${COLLECTION:-default} --collection ${COLLECTION:-}
    profiles:
      - workers-collection

  # Воркер второго этапа классификации
  classification-worker-stage2-1:
    build: .
    env_file:
      - .env
    environment:
      - WORKER_ID=stage2_worker_${WORKER_NUMBER:-1}
      - REDIS_URL=redis://redis:6379
      - CLASSIFICATION_BATCH_SIZE=15
    depends_on:
      - redis
    volumes:
      - ./src/data:/app/src/data:ro
    restart: unless-stopped
    command: python -m src.workers.classification_worker_stage2 --worker-id stage2_worker_${WORKER_NUMBER:-1}
    profiles:
      - workers-stage2

volumes:
  redis_data:

# Примеры использования:
#
# Запуск API:
# docker-compose up -d api redis
#
# Запуск миграции:
# docker-compose --profile migration up migration-worker
#
# Запуск воркеров для всех коллекций:
# docker-compose --profile workers up classification-worker-1
# docker-compose --profile workers-stage2 up classification-worker-stage2-1
#
# Запуск воркера для конкретной коллекции (только первый этап):
# COLLECTION=electronics docker-compose --profile workers-collection up classification-worker-collection
#
# Масштабирование воркеров:
# docker-compose --profile workers up --scale classification-worker-1=3
# docker-compose --profile workers-stage2 up --scale classification-worker-stage2-1=2