version: '3.8'

services:
  # Target MongoDB для хранения результатов классификации
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=okpd_classifier
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Переопределяем для Docker network
      - TARGET_MONGO_HOST=mongodb
      - REDIS_URL=redis://redis:6379
      # Прокси настройки (если указаны в .env)
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - SOCKS_PROXY=${SOCKS_PROXY}
      - NO_PROXY=localhost,127.0.0.1,mongodb,redis
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

  migration-worker:
    build: .
    env_file:
      - .env
    environment:
      # Переопределяем для Docker network
      - TARGET_MONGO_HOST=mongodb
      - REDIS_URL=redis://redis:6379
      # Прокси настройки (если указаны в .env)
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - SOCKS_PROXY=${SOCKS_PROXY}
      - NO_PROXY=localhost,127.0.0.1,mongodb,redis
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    command: python -m src.workers.migration_worker

  # Только один classification worker для избежания rate limit!
  classification-worker:
    build: .
    env_file:
      - .env
    environment:
      - WORKER_ID=worker_1
      # Переопределяем для Docker network
      - TARGET_MONGO_HOST=mongodb
      - REDIS_URL=redis://redis:6379
      # Важные настройки для rate limit
      - CLASSIFICATION_BATCH_SIZE=10
      - RATE_LIMIT_DELAY=10
      - MAX_RETRIES=3
      # Прокси настройки (если указаны в .env)
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - SOCKS_PROXY=${SOCKS_PROXY}
      - NO_PROXY=localhost,127.0.0.1,mongodb,redis
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    command: python -m src.workers.classification_worker --worker-id worker_1

volumes:
  mongo_data:
  redis_data: