version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

  migration-worker:
    build: .
    env_file:
      - .env
    command: python -m src.workers.migration_worker

  classification-worker:
    build: .
    env_file:
      - .env
    environment:
      - WORKER_ID=worker_${WORKER_NUMBER:-1}
    depends_on:
      - redis
    command: python -m src.workers.classification_worker --worker-id worker_${WORKER_NUMBER:-1}
    deploy:
      replicas: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  redis_data: